### PR TITLE
Update to upstream repository

### PR DESCRIPTION
**Pull request by nos86**
[Review on Reviewable](https://reviewable.io/reviews/grodansparadis/vscp_firmware/7)

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/grodansparadis%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1358883%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/grodansparadis/vscp_firmware/pull/7%23issuecomment-106306901%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%5Cn%5Cn%5Cn%5CnReview%20status%3A%20%3Ashipit%3A%20all%20files%20reviewed%2C%20all%20discussions%20resolved%2C%20all%20commit%20checks%20successful.%5CnReviewed%20files%3A%5Cn-%20.gitignore%20%40%20r1%5Cn-%20avr/AT90CAN32_Latching_Relay/src/latchingrelay.hex%20%40%20r1%5Cn-%20avr/AT90CAN32_Latching_Relay/src/latchingrelay_eeprom.hex%20%40%20r1%5Cn-%20common/vscp_class.h%20%40%20r1%5Cn-%20common/vscp_type.h%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/funclist%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/Makefile%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/configurations.xml%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/Makefile-C18_18F4580.mk%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/Makefile-genesis.properties%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/Makefile-impl.mk%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/Makefile-local-C18_18F4580.mk%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/Makefile-variables.mk%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/Package-C18_18F4580.bash%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/private/configurations.xml%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/private/private.xml%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/private/SuppressibleMessageMemo.properties%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/project.properties%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/nbproject/project.xml%20%40%20r1%5Cn-%20pic/augusto/project/Augusto.X/project_information.txt%20%40%20r1%5Cn-%20pic/augusto/project/augusto_eeprom_layout.h%20%40%20r1%5Cn-%20pic/augusto/project/driver.c%20%40%20r1%5Cn-%20pic/augusto/project/driver.h%20%40%20r1%5Cn-%20pic/augusto/project/main.c%20%40%20r1%5Cn-%20pic/augusto/project/main.h%20%40%20r1%5Cn-%20pic/augusto/project/vscp_appLayer.c%20%40%20r1%5Cn-%20pic/augusto/project/vscp_appLayer.h%20%40%20r1%5Cn-%20pic/augusto/project/vscp_compiler.h%20%40%20r1%5Cn-%20pic/augusto/project/vscp_projdefs.h%20%40%20r1%5Cn-%20pic/chicago/mdf/hass_011.xml%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/funclist%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/Makefile%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/configurations.xml%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/Makefile-C18_18F4580.mk%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/Makefile-genesis.properties%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/Makefile-impl.mk%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/Makefile-local-C18_18F4580.mk%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/Makefile-variables.mk%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/Package-C18_18F4580.bash%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/private/configurations.xml%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/private/private.xml%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/private/SuppressibleMessageMemo.properties%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/project.properties%20%40%20r1%5Cn-%20pic/chicago/project/Chicago.X/nbproject/project.xml%20%40%20r1%5Cn-%20pic/chicago/project/main.c%20%40%20r1%5Cn-%20pic/chicago/project/main.h%20%40%20r1%5Cn-%20pic/chicago/project/vscp_compiler.h%20%40%20r1%5Cn-%20pic/chicago/project/vscp_projdefs.h%20%40%20r1%5Cn-%20pic/chicago/project/windowEngine.c%20%40%20r1%5Cn-%20pic/chicago/project/windowEngine.h%20%40%20r1%5Cn-%20pic/common/can18f.c%20%40%20r1%5Cn%5Cn---%5Cn%5Cn%5Cn%5CnComments%20from%20the%20%5Breview%20on%20Reviewable.io%5D%28https%3A//reviewable.io%3A443/reviews/grodansparadis/vscp_firmware/7%29%5Cn%3C%21--%20Sent%20from%20Reviewable.io%20--%3E%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-28T13%3A20%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1358883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/grodansparadis%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-28T13%3A25%3A32Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1358883%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/grodansparadis%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/grodansparadis/vscp_firmware/pull/7%23issuecomment-106306901%22%2C%20%22https%3A//github.com/grodansparadis/vscp_firmware/pull/7%23issuecomment-106307867%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/grodansparadis'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/grodansparadis/vscp_firmware/pull/7#issuecomment-106306901'>General Comment</a></b>
- <a href='https://github.com/grodansparadis'></a> Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- .gitignore @ r1
- avr/AT90CAN32_Latching_Relay/src/latchingrelay.hex @ r1
- avr/AT90CAN32_Latching_Relay/src/latchingrelay_eeprom.hex @ r1
- common/vscp_class.h @ r1
- common/vscp_type.h @ r1
- pic/augusto/project/Augusto.X/funclist @ r1
- pic/augusto/project/Augusto.X/Makefile @ r1
- pic/augusto/project/Augusto.X/nbproject/configurations.xml @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-C18_18F4580.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-genesis.properties @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-impl.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-local-C18_18F4580.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-variables.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Package-C18_18F4580.bash @ r1
- pic/augusto/project/Augusto.X/nbproject/private/configurations.xml @ r1
- pic/augusto/project/Augusto.X/nbproject/private/private.xml @ r1
- pic/augusto/project/Augusto.X/nbproject/private/SuppressibleMessageMemo.properties @ r1
- pic/augusto/project/Augusto.X/nbproject/project.properties @ r1
- pic/augusto/project/Augusto.X/nbproject/project.xml @ r1
- pic/augusto/project/Augusto.X/project_information.txt @ r1
- pic/augusto/project/augusto_eeprom_layout.h @ r1
- pic/augusto/project/driver.c @ r1
- pic/augusto/project/driver.h @ r1
- pic/augusto/project/main.c @ r1
- pic/augusto/project/main.h @ r1
- pic/augusto/project/vscp_appLayer.c @ r1
- pic/augusto/project/vscp_appLayer.h @ r1
- pic/augusto/project/vscp_compiler.h @ r1
- pic/augusto/project/vscp_projdefs.h @ r1
- pic/chicago/mdf/hass_011.xml @ r1
- pic/chicago/project/Chicago.X/funclist @ r1
- pic/chicago/project/Chicago.X/Makefile @ r1
- pic/chicago/project/Chicago.X/nbproject/configurations.xml @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-C18_18F4580.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-genesis.properties @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-impl.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-local-C18_18F4580.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-variables.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Package-C18_18F4580.bash @ r1
- pic/chicago/project/Chicago.X/nbproject/private/configurations.xml @ r1
- pic/chicago/project/Chicago.X/nbproject/private/private.xml @ r1
- pic/chicago/project/Chicago.X/nbproject/private/SuppressibleMessageMemo.properties @ r1
- pic/chicago/project/Chicago.X/nbproject/project.properties @ r1
- pic/chicago/project/Chicago.X/nbproject/project.xml @ r1
- pic/chicago/project/main.c @ r1
- pic/chicago/project/main.h @ r1
- pic/chicago/project/vscp_compiler.h @ r1
- pic/chicago/project/vscp_projdefs.h @ r1
- pic/chicago/project/windowEngine.c @ r1
- pic/chicago/project/windowEngine.h @ r1
- pic/common/can18f.c @ r1
---
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grodansparadis/vscp_firmware/7)

<a href='https://www.codereviewhub.com/grodansparadis/vscp_firmware/pull/7?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/grodansparadis/vscp_firmware/pull/7?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/grodansparadis/vscp_firmware/pull/7?approve=0'></a>&nbsp;<a href='https://github.com/grodansparadis/vscp_firmware/pull/7'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by grodansparadis** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- .gitignore @ r1
- avr/AT90CAN32_Latching_Relay/src/latchingrelay.hex @ r1
- avr/AT90CAN32_Latching_Relay/src/latchingrelay_eeprom.hex @ r1
- common/vscp_class.h @ r1
- common/vscp_type.h @ r1
- pic/augusto/project/Augusto.X/funclist @ r1
- pic/augusto/project/Augusto.X/Makefile @ r1
- pic/augusto/project/Augusto.X/nbproject/configurations.xml @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-C18_18F4580.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-genesis.properties @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-impl.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-local-C18_18F4580.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Makefile-variables.mk @ r1
- pic/augusto/project/Augusto.X/nbproject/Package-C18_18F4580.bash @ r1
- pic/augusto/project/Augusto.X/nbproject/private/configurations.xml @ r1
- pic/augusto/project/Augusto.X/nbproject/private/private.xml @ r1
- pic/augusto/project/Augusto.X/nbproject/private/SuppressibleMessageMemo.properties @ r1
- pic/augusto/project/Augusto.X/nbproject/project.properties @ r1
- pic/augusto/project/Augusto.X/nbproject/project.xml @ r1
- pic/augusto/project/Augusto.X/project_information.txt @ r1
- pic/augusto/project/augusto_eeprom_layout.h @ r1
- pic/augusto/project/driver.c @ r1
- pic/augusto/project/driver.h @ r1
- pic/augusto/project/main.c @ r1
- pic/augusto/project/main.h @ r1
- pic/augusto/project/vscp_appLayer.c @ r1
- pic/augusto/project/vscp_appLayer.h @ r1
- pic/augusto/project/vscp_compiler.h @ r1
- pic/augusto/project/vscp_projdefs.h @ r1
- pic/chicago/mdf/hass_011.xml @ r1
- pic/chicago/project/Chicago.X/funclist @ r1
- pic/chicago/project/Chicago.X/Makefile @ r1
- pic/chicago/project/Chicago.X/nbproject/configurations.xml @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-C18_18F4580.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-genesis.properties @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-impl.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-local-C18_18F4580.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Makefile-variables.mk @ r1
- pic/chicago/project/Chicago.X/nbproject/Package-C18_18F4580.bash @ r1
- pic/chicago/project/Chicago.X/nbproject/private/configurations.xml @ r1
- pic/chicago/project/Chicago.X/nbproject/private/private.xml @ r1
- pic/chicago/project/Chicago.X/nbproject/private/SuppressibleMessageMemo.properties @ r1
- pic/chicago/project/Chicago.X/nbproject/project.properties @ r1
- pic/chicago/project/Chicago.X/nbproject/project.xml @ r1
- pic/chicago/project/main.c @ r1
- pic/chicago/project/main.h @ r1
- pic/chicago/project/vscp_compiler.h @ r1
- pic/chicago/project/vscp_projdefs.h @ r1
- pic/chicago/project/windowEngine.c @ r1
- pic/chicago/project/windowEngine.h @ r1
- pic/common/can18f.c @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/grodansparadis/vscp_firmware/7)

**Comment by grodansparadis** [comment]
:shipit:

**Comment by nos86** [comment]
Hello,

I'm sorry, I'm a newbie with GitHub and last pull request was an error.
Please, undo it, I don't want to create any glitch with other developers.

As soon as my projects will be stable, I'll send you a specific pull request with only project contents.

Thanks a lot and sorry again,
Salvo

**Comment by grodansparadis** [comment]
Hi Salov,

are you sure.  The only problem I saw was the vscp_class&type.h which is 
copies from the vscp_software repository and that should not be changed 
here and the

  * avr/AT90CAN32_Latching_Relay/src/latchingrelay.hex @ r1
  * avr/AT90CAN32_Latching_Relay/src/latchingrelay_eeprom.hex @ r1

which I have reverted. So only your new stuff got added.

Do you want me to revert it anyway?

Cheers
/Ake

Salvo Musumeci skrev den 2015-05-28 17:00:
>
> Hello,
>
> I'm sorry, I'm a newbie with GitHub and last pull request was an error.
> Please, undo it, I don't want to create any glitch with other developers.
>
> As soon as my projects will be stable, I'll send you a specific pull 
> request with only project contents.
>
> Thanks a lot and sorry again,
> Salvo
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/pull/7#issuecomment-106380103>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
The hex files for the avr latch project was removed due to .hex included 
in .gitignore but I have restored them again so there should be nothing 
else changed than the files you added now.  Git can really be a mouthful 
sometime.

Salvo Musumeci skrev den 2015-05-28 17:00:
>
> Hello,
>
> I'm sorry, I'm a newbie with GitHub and last pull request was an error.
> Please, undo it, I don't want to create any glitch with other developers.
>
> As soon as my projects will be stable, I'll send you a specific pull 
> request with only project contents.
>
> Thanks a lot and sorry again,
> Salvo
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/pull/7#issuecomment-106380103>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
@mamac removed your he files form the latch project today by mistake. Restored now again. My fault. Just in case you wounder what is happening

**Comment by nos86** [comment]
Ciao,

most important stuff is that no corrupted files are present for other users.
Regarding my project, I suggest you to remove it and as soon as I have a stable version, I'll pull it in your repository.

Thanks and sorry again,
Salvo

**Comment by grodansparadis** [comment]
No problem Salvo. I fix that.  Have a nice weekend down there in the sun 
(I hope).

/Ake


Salvo Musumeci skrev den 2015-05-29 11:53:
>
> Ciao,
>
> most important stuff is that no corrupted files are present for other 
> users.
> Regarding my project, I suggest you to remove it and as soon as I have 
> a stable version, I'll pull it in your repository.
>
> Thanks and sorry again,
> Salvo
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_firmware/pull/7#issuecomment-106761222>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Pull request merged**
